version: '3.8'
services:

# Note: `- DISABLE_HTTPS=true` is used for behave.

  # For running behave:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app  # Mount only the app directory
      - ${SECRETS_DIR_PATH}:/run/secrets:ro   # read‑only mount
      - ./.env:/app/.env  # Mount the .env file too 

    environment:
      - FLASK_APP=app:create_app
      - FLASK_ENV=development
      - FLASK_RUN_PORT=5000
      - DISABLE_HTTPS=true  # HTTPS off for Selenium.
    command: >
      flask run --debug
        --host=0.0.0.0


  # For running pytest:
  test:
    build: .
    volumes:
      - ./app:/app
      - ./tests:/app/tests        # Tests volume
      - ./pyproject.toml:/app/pyproject.toml  # Add this line
    environment:
      - FLASK_APP=app:create_app
      # - FLASK_ENV=testing
      - FLASK_ENV=${ENV}    # ← This will read 'development' from .env

    # Variant 1: Used with vim-test, which runs pytest itself:
    command: tail -f /dev/null  # Keeps the container running.

    # Variant 2: When used as a standalone test runner:
    # command: pytest -x --spec --cov=app --cov-report=term-missing --tb=short

    depends_on:
      - app



  bdd-tests:
      image: mcr.microsoft.com/playwright/python:v1.40.0-focal
      profiles:
        - ci  # ONLY runs when you explicitly enable this profile
      working_dir: /app
      volumes:
        - ./features:/app/features
        - ./app:/app/app
      environment:
        - BASE_URL=http://app:5000
      command: >
        bash -c "
          pip install behave requests playwright &&
          playwright install chromium &&
          behave features/ -D browser=chromium -D ui=false
        "
